name: formation_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: any

  # UI
  flutter_svg: 2.2.3
  sliver_tools: 0.2.12

  ## Routing
  go_router: 17.0.1

  ## State Management
  provider: 6.1.5+1
  flutter_bloc: 9.1.1

  ## Network
  dio: 5.9.0
  retrofit: 4.9.1
  json_annotation: 4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  ## Network
  retrofit_generator: 10.2.0
  json_serializable: any
  build_runner: 2.10.4

flutter:

  uses-material-design: true

  assets:
    - res/drawables/
    - res/svg/

  fonts:
    - family: AppIcons
      fonts:
        - asset: res/fonts/app_icons.ttf
    - family: Avenir
      fonts:
        - asset: res/fonts/Avenir-Light.ttf
          weight: 300
        - asset: res/fonts/Avenir-Regular.ttf
          weight: 400
        - asset: res/fonts/Avenir-Medium.ttf
          weight: 500
        - asset: res/fonts/Avenir-Black.ttf
          weight: 900

  generate: true